services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: appdb
    ports: ["3306:3306"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-psecret"]
      interval: 5s
      timeout: 3s
      retries: 40

  customers-api:
    build: ./customers-api
    env_file: ./customers-api/.env
    depends_on: { mysql: { condition: service_healthy } }
    ports: ["3001:3001"]

  orders-api:
    build: ./orders-api
    env_file: ./orders-api/.env
    depends_on: { mysql: { condition: service_healthy } }
    ports: ["3002:3002"]
